name: Test Formulaire PHP

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer PHP
      - name: Install PHP
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli

      # Étape 3 : Démarrer le serveur PHP
      - name: Start PHP server
        run: |
          php -S 0.0.0.0:8000 -t . &  # Lancer le serveur PHP en arrière-plan
          sleep 5  # Attendre 5 secondes que le serveur démarre

      # Étape 4 : Vérifier que le formulaire est accessible
      - name: Test if form is accessible
        run: |
          curl --fail http://localhost:8000/form.php  # Vérifier si la page est accessible
          
      # Étape 5 : Installer TestCafe
      - name: Install TestCafe
        run: |
          npm install -g testcafe

      # Étape 6 : Exécuter les tests TestCafe
      - name: Run TestCafe tests
        run: |
          testcafe "firefox:headless" test_form.js
